package com.junshijia.ecs.domain;

import java.util.ArrayList;
import java.util.List;

public class TenMinMemory{

	private List<Float> HMI_IReg155;
	private List<Float> HMI_IReg167;
	private List<Float> HMI_IReg199;
	private List<Float> HMI_IReg101;
	private List<Float> HMI_IReg102;
	private List<Float> HMI_IReg103;
	private List<Float> HMI_IReg104;
	private List<Float> HMI_IReg105;
	private List<Float> HMI_IReg106;
	private List<Float> HMI_IReg107;
	private List<Float> HMI_IReg110;
	private List<Float> HMI_IReg118;
	private List<Float> HMI_IReg121;
	private List<Float> HMI_IReg122;
	private List<Float> HMI_IReg201;
	private List<Float> HMI_IReg203;
	private List<Float> HMI_IReg210;
	private List<Float> HMI_IReg206;
	private List<Float> HMI_IReg214;
	private List<Float> HMI_IReg216;
	private List<Float> HMI_IReg224;
	private List<Float> HMI_IReg237;
	private List<Float> HMI_IReg238;
	private List<Float> HMI_IReg239;
	private List<Float> HMI_IReg240;
	private List<Float> HMI_IReg241;
	private List<Float> HMI_IReg242;
	private List<Float> HMI_IReg243;
	private List<Float> HMI_IReg244;
	private List<Float> HMI_IReg245;
	private List<Float> HMI_IReg248;
	private List<Float> HMI_IReg1405;
	private List<Float> HMI_IReg1406;
	private List<Float> HMI_IReg1407;
	private List<Float> HMI_IReg1408;
	private List<Float> HMI_IReg1418;
	private List<Float> HMI_IReg1419;
	private List<Float> HMI_IReg1420;
	private List<Float> HMI_IReg1422;
	private List<Float> HMI_IReg1423;
	private List<Float> HMI_IReg1426;
	private List<Float> HMI_IReg1611;
	private List<Float> HMI_IReg1612;
	private List<Float> HMI_IReg1613;
	private List<Float> HMI_IReg1637;
	private List<Float> HMI_IReg1638;
	private List<Float> HMI_IReg1639;
	private List<Float> HMI_IReg1640;
	private List<Float> HMI_IReg1641;
	private List<Float> HMI_IReg1642;
	private List<Float> HMI_IReg1643;
	private List<Float> HMI_IReg1644;
	private List<Float> HMI_IReg1645;
	private List<Float> HMI_IReg1646;
	private List<Float> HMI_IReg1665;
	private List<Float> HMI_IReg1666;
	private List<Float> HMI_IReg1677;
	private List<Float> HMI_IReg1678;
	private List<Float> HMI_IReg1691;
	private List<Float> HMI_IReg1692;
	private List<Float> HMI_IReg1693;
	private List<Float> HMI_IReg1694;
	private List<Float> HMI_IReg1508;
	private List<Float> HMI_IReg1514;
	private List<Float> HMI_IReg1515;
	private List<Float> HMI_IReg1516;
	private List<Float> HMI_IReg1517;
	private List<Float> HMI_IReg1518;
	private List<Float> HMI_IReg1519;
	private List<Float> HMI_IReg6;
	private List<Float> HMI_IReg7;
	private List<Float> HMI_IReg8;
	private List<Float> HMI_IReg9;

	public TenMinMemory() {
		this.HMI_IReg155 = new ArrayList<>();
		this.HMI_IReg167 = new ArrayList<>();
		this.HMI_IReg199 = new ArrayList<>();
		this.HMI_IReg101 = new ArrayList<>();
		this.HMI_IReg102 = new ArrayList<>();
		this.HMI_IReg103 = new ArrayList<>();
		this.HMI_IReg104 = new ArrayList<>();
		this.HMI_IReg105 = new ArrayList<>();
		this.HMI_IReg106 = new ArrayList<>();
		this.HMI_IReg107 = new ArrayList<>();
		this.HMI_IReg110 = new ArrayList<>();
		this.HMI_IReg118 = new ArrayList<>();
		this.HMI_IReg121 = new ArrayList<>();
		this.HMI_IReg122 = new ArrayList<>();
		this.HMI_IReg201 = new ArrayList<>();
		this.HMI_IReg203 = new ArrayList<>();
		this.HMI_IReg210 = new ArrayList<>();
		this.HMI_IReg206 = new ArrayList<>();
		this.HMI_IReg214 = new ArrayList<>();
		this.HMI_IReg216 = new ArrayList<>();
		this.HMI_IReg224 = new ArrayList<>();
		this.HMI_IReg237 = new ArrayList<>();
		this.HMI_IReg238 = new ArrayList<>();
		this.HMI_IReg239 = new ArrayList<>();
		this.HMI_IReg240 = new ArrayList<>();
		this.HMI_IReg241 = new ArrayList<>();
		this.HMI_IReg242 = new ArrayList<>();
		this.HMI_IReg243 = new ArrayList<>();
		this.HMI_IReg244 = new ArrayList<>();
		this.HMI_IReg245 = new ArrayList<>();
		this.HMI_IReg248 = new ArrayList<>();
		this.HMI_IReg1405 = new ArrayList<>();
		this.HMI_IReg1406 = new ArrayList<>();
		this.HMI_IReg1407 = new ArrayList<>();
		this.HMI_IReg1408 = new ArrayList<>();
		this.HMI_IReg1418 = new ArrayList<>();
		this.HMI_IReg1419 = new ArrayList<>();
		this.HMI_IReg1420 = new ArrayList<>();
		this.HMI_IReg1422 = new ArrayList<>();
		this.HMI_IReg1423 = new ArrayList<>();
		this.HMI_IReg1426 = new ArrayList<>();
		this.HMI_IReg1611 = new ArrayList<>();
		this.HMI_IReg1612 = new ArrayList<>();
		this.HMI_IReg1613 = new ArrayList<>();
		this.HMI_IReg1637 = new ArrayList<>();
		this.HMI_IReg1638 = new ArrayList<>();
		this.HMI_IReg1639 = new ArrayList<>();
		this.HMI_IReg1640 = new ArrayList<>();
		this.HMI_IReg1641 = new ArrayList<>();
		this.HMI_IReg1642 = new ArrayList<>();
		this.HMI_IReg1643 = new ArrayList<>();
		this.HMI_IReg1644 = new ArrayList<>();
		this.HMI_IReg1645 = new ArrayList<>();
		this.HMI_IReg1646 = new ArrayList<>();
		this.HMI_IReg1665 = new ArrayList<>();
		this.HMI_IReg1666 = new ArrayList<>();
		this.HMI_IReg1677 = new ArrayList<>();
		this.HMI_IReg1678 = new ArrayList<>();
		this.HMI_IReg1691 = new ArrayList<>();
		this.HMI_IReg1692 = new ArrayList<>();
		this.HMI_IReg1693 = new ArrayList<>();
		this.HMI_IReg1694 = new ArrayList<>();
		this.HMI_IReg1508 = new ArrayList<>();
		this.HMI_IReg1514 = new ArrayList<>();
		this.HMI_IReg1515 = new ArrayList<>();
		this.HMI_IReg1516 = new ArrayList<>();
		this.HMI_IReg1517 = new ArrayList<>();
		this.HMI_IReg1518 = new ArrayList<>();
		this.HMI_IReg1519 = new ArrayList<>();
		this.HMI_IReg6 = new ArrayList<>();
		this.HMI_IReg7 = new ArrayList<>();
		this.HMI_IReg8 = new ArrayList<>();
		this.HMI_IReg9 = new ArrayList<>();
	}
}
